#!/bin/sh
# properties = {"type": "single", "rule": "generate_plots", "local": false, "input": ["results_batch20/Blood_draw_1/Blood_draw_1.uncorrected.coverage.tsv", "results_batch20/Blood_draw_2/Blood_draw_2.uncorrected.coverage.tsv", "results_batch20/Blood_draw_3/Blood_draw_3.uncorrected.coverage.tsv", "results_batch20/Blood_draw_1/Blood_draw_1.GC_corrected.coverage.tsv", "results_batch20/Blood_draw_2/Blood_draw_2.GC_corrected.coverage.tsv", "results_batch20/Blood_draw_3/Blood_draw_3.GC_corrected.coverage.tsv"], "output": ["results_batch20/plots/site_ESR1.pdf", "results_batch20/plots/site_FOXA1.pdf", "results_batch20/plots/site_GATA3.pdf", "results_batch20/plots/site_PGR.pdf", "results_batch20/plots/site_CTCF.pdf"], "wildcards": {}, "params": {"in_dir": "results_batch20", "samples_yaml": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/config/samples.yaml", "mappability_correction": "False", "save_window": "-1000 1000", "step": 15, "individual": false, "results_dir": "results_batch20", "griffin_plot_script": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/scripts//griffin_plot.py", "tmp_dir": "results_batch20/tmp"}, "log": [], "threads": 1, "resources": {}, "jobid": 4, "cluster": {"partition": "htc", "time": "48:00:00", "mem": "8G", "ncpus": 1, "ntasks": 1, "output": "logs/cluster/generate_plots.%A.out", "JobName": "generate_plots"}}
 cd /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling && \
/ix1/alee/LO_LAB/Personal/Daisong/griffin_env_new/bin/python \
-m snakemake results_batch20/plots/site_ESR1.pdf --snakefile /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/griffin_nucleosome_profiling.snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/.snakemake/tmp.wr5q62f1 results_batch20/Blood_draw_1/Blood_draw_1.uncorrected.coverage.tsv results_batch20/Blood_draw_2/Blood_draw_2.uncorrected.coverage.tsv results_batch20/Blood_draw_3/Blood_draw_3.uncorrected.coverage.tsv results_batch20/Blood_draw_1/Blood_draw_1.GC_corrected.coverage.tsv results_batch20/Blood_draw_2/Blood_draw_2.GC_corrected.coverage.tsv results_batch20/Blood_draw_3/Blood_draw_3.GC_corrected.coverage.tsv --latency-wait 60 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://github.com/snakemake/snakemake-wrappers/raw/ \
   --allowed-rules generate_plots --nocolor --notemp --no-hooks --nolock \
--mode 2  && touch /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/.snakemake/tmp.wr5q62f1/4.jobfinished || (touch /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/.snakemake/tmp.wr5q62f1/4.jobfailed; exit 1)

