#!/bin/sh
# properties = {"type": "single", "rule": "calc_cov", "local": false, "input": ["/ix1/alee/LO_LAB/General/Lab_Data/20250610_ILC_ctDNA_shWGS_01_Daisong/bam/TP25-M18.bam", "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_GC_and_mappability_correction/results_batch19/GC_bias/TP25-M18.GC_bias.txt"], "output": ["results_batch20/tmp/TP25-M18/tmp_bigWig/TP25-M18.uncorrected.bw", "results_batch20/tmp/TP25-M18/tmp_bigWig/TP25-M18.GC_corrected.bw", "results_batch20/tmp/TP25-M18/tmp_pybedtools"], "wildcards": {"samples": "TP25-M18"}, "params": {"sample_name": "TP25-M18", "mappability_bias": "none", "mappability_correction": "False", "tmp_dir": "results_batch20/tmp", "reference_genome": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/Ref/hg38.fa", "mappability_bw": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/Ref/k100.Umap.MultiTrackMappability.bw", "chrom_sizes_path": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/Ref/hg38.standard.chrom.sizes", "sites_yaml": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/config/sites.yaml", "griffin_scripts_dir": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/scripts/", "griffin_coverage_script": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/scripts//griffin_coverage.py", "chrom_column": "Chrom", "position_column": "position", "strand_column": "Strand", "chroms": "chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22", "norm_window": "-5000 5000", "size_range": "100 200", "map_quality": 20, "number_of_sites": "none", "sort_by": "none", "ascending": "none", "CPU": 8}, "log": [], "threads": 1, "resources": {}, "jobid": 190, "cluster": {"partition": "htc", "time": "48:00:00", "mem": "10G", "ncpus": 8, "ntasks": 1, "output": "logs/cluster/calc_cov.TP25-M18.%A.out", "JobName": "calc_cov.TP25-M18"}}
 cd /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling && \
/ix1/alee/LO_LAB/Personal/Daisong/griffin_env_new/bin/python \
-m snakemake results_batch20/tmp/TP25-M18/tmp_bigWig/TP25-M18.uncorrected.bw --snakefile /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/griffin_nucleosome_profiling.snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/.snakemake/tmp.k0rd_lsa /ix1/alee/LO_LAB/General/Lab_Data/20250610_ILC_ctDNA_shWGS_01_Daisong/bam/TP25-M18.bam /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_GC_and_mappability_correction/results_batch19/GC_bias/TP25-M18.GC_bias.txt --latency-wait 60 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://github.com/snakemake/snakemake-wrappers/raw/ \
   --allowed-rules calc_cov --nocolor --notemp --no-hooks --nolock \
--mode 2  && touch /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/.snakemake/tmp.k0rd_lsa/190.jobfinished || (touch /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/.snakemake/tmp.k0rd_lsa/190.jobfailed; exit 1)

