#!/bin/sh
# properties = {"type": "single", "rule": "merge_sites", "local": false, "input": ["results_batch1/tmp/TP18-M748/tmp_bigWig/TP18-M748.uncorrected.bw", "results_batch1/tmp/TP18-M748/tmp_bigWig/TP18-M748.GC_corrected.bw"], "output": ["results_batch1/TP18-M748/TP18-M748.uncorrected.coverage.tsv", "results_batch1/TP18-M748/TP18-M748.GC_corrected.coverage.tsv", "results_batch1/tmp/TP18-M748/tmp_pybedtools2"], "wildcards": {"samples": "TP18-M748"}, "params": {"sample_name": "TP18-M748", "tmp_dir": "results_batch1/tmp", "results_dir": "results_batch1", "mappability_correction": "False", "GC_map_corrected_bw": "none", "mappability_bw": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/Ref/k100.Umap.MultiTrackMappability.bw", "chrom_sizes_path": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/Ref/hg38.standard.chrom.sizes", "sites_yaml": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/config/sites.yaml", "griffin_scripts_dir": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/scripts/", "griffin_merge_sites_script": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/scripts//griffin_merge_sites.py", "chrom_column": "Chrom", "position_column": "position", "strand_column": "Strand", "chroms": "chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22", "norm_window": "-5000 5000", "save_window": "-1000 1000", "center_window": "-30 30", "fft_window": "-960 960", "fft_index": 10, "smoothing_length": 165, "encode_exclude": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/Ref/encode_unified_GRCh38_exclusion_list.bed", "centromeres": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/Ref/hg38_centromeres.bed", "gaps": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/Ref/hg38_gaps.bed", "patches": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/Ref/hg38_fix_patches.bed", "alternative_haplotypes": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/Ref/hg38_alternative_haplotypes.bed", "step": 15, "CNA_normalization": false, "individual": false, "smoothing": true, "exclude_outliers": true, "exclude_zero_mappability": true, "number_of_sites": "none", "sort_by": "none", "ascending": "none", "CPU": 8}, "log": [], "threads": 1, "resources": {}, "jobid": 3, "cluster": {"partition": "htc", "time": "48:00:00", "mem": "10G", "ncpus": 8, "ntasks": 1, "output": "logs/cluster/merge_sites.TP18-M748.%A.out", "JobName": "merge_sites.TP18-M748"}}
 cd /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling && \
/ix1/alee/LO_LAB/Personal/Daisong/griffin_env_new/bin/python \
-m snakemake results_batch1/TP18-M748/TP18-M748.GC_corrected.coverage.tsv --snakefile /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/griffin_nucleosome_profiling.snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/.snakemake/tmp.086sn1cp results_batch1/tmp/TP18-M748/tmp_bigWig/TP18-M748.uncorrected.bw results_batch1/tmp/TP18-M748/tmp_bigWig/TP18-M748.GC_corrected.bw --latency-wait 60 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://github.com/snakemake/snakemake-wrappers/raw/ \
 --configfiles /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/config/samples.batch1.yaml /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/config/config.batch1.yaml  --allowed-rules merge_sites --nocolor --notemp --no-hooks --nolock \
--mode 2  && touch /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/.snakemake/tmp.086sn1cp/3.jobfinished || (touch /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/.snakemake/tmp.086sn1cp/3.jobfailed; exit 1)

