#!/bin/sh
# properties = {"type": "single", "rule": "generate_plots", "local": false, "input": ["results_batch12/TP23-M221/TP23-M221.uncorrected.coverage.tsv", "results_batch12/TP23-M239/TP23-M239.uncorrected.coverage.tsv", "results_batch12/TP23-M286/TP23-M286.uncorrected.coverage.tsv", "results_batch12/TP23-M332/TP23-M332.uncorrected.coverage.tsv", "results_batch12/TP23-M365/TP23-M365.uncorrected.coverage.tsv", "results_batch12/TP23-M221/TP23-M221.GC_corrected.coverage.tsv", "results_batch12/TP23-M239/TP23-M239.GC_corrected.coverage.tsv", "results_batch12/TP23-M286/TP23-M286.GC_corrected.coverage.tsv", "results_batch12/TP23-M332/TP23-M332.GC_corrected.coverage.tsv", "results_batch12/TP23-M365/TP23-M365.GC_corrected.coverage.tsv"], "output": ["results_batch12/plots/site_ESR1.pdf", "results_batch12/plots/site_FOXA1.pdf", "results_batch12/plots/site_GATA3.pdf", "results_batch12/plots/site_PGR.pdf", "results_batch12/plots/site_CTCF.pdf"], "wildcards": {}, "params": {"in_dir": "results_batch12", "samples_yaml": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/config/samples.yaml", "mappability_correction": "False", "save_window": "-1000 1000", "step": 15, "individual": false, "results_dir": "results_batch12", "griffin_plot_script": "/ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/scripts//griffin_plot.py", "tmp_dir": "results_batch12/tmp"}, "log": [], "threads": 1, "resources": {}, "jobid": 6, "cluster": {"partition": "htc", "time": "48:00:00", "mem": "8G", "ncpus": 1, "ntasks": 1, "output": "logs/cluster/generate_plots.%A.out", "JobName": "generate_plots"}}
 cd /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling && \
/ix1/alee/LO_LAB/Personal/Daisong/griffin_env_new/bin/python \
-m snakemake results_batch12/plots/site_ESR1.pdf --snakefile /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/griffin_nucleosome_profiling.snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/.snakemake/tmp._bli0v52 results_batch12/TP23-M221/TP23-M221.uncorrected.coverage.tsv results_batch12/TP23-M239/TP23-M239.uncorrected.coverage.tsv results_batch12/TP23-M286/TP23-M286.uncorrected.coverage.tsv results_batch12/TP23-M332/TP23-M332.uncorrected.coverage.tsv results_batch12/TP23-M365/TP23-M365.uncorrected.coverage.tsv results_batch12/TP23-M221/TP23-M221.GC_corrected.coverage.tsv results_batch12/TP23-M239/TP23-M239.GC_corrected.coverage.tsv results_batch12/TP23-M286/TP23-M286.GC_corrected.coverage.tsv results_batch12/TP23-M332/TP23-M332.GC_corrected.coverage.tsv results_batch12/TP23-M365/TP23-M365.GC_corrected.coverage.tsv --latency-wait 60 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://github.com/snakemake/snakemake-wrappers/raw/ \
 --configfiles /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/config/samples.batch12.yaml /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/config/config.batch12.yaml  --allowed-rules generate_plots --nocolor --notemp --no-hooks --nolock \
--mode 2  && touch /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/.snakemake/tmp._bli0v52/6.jobfinished || (touch /ix1/alee/LO_LAB/Personal/Daisong/Projects/APOLLO/shWGS/Griffin/griffin_nucleosome_profiling/.snakemake/tmp._bli0v52/6.jobfailed; exit 1)

